Forex strategy research protocol — AUD/JPY M15 LONG template
Version: 2026-09-24  
Status: Reusable research workflow, illustrated by AUD/JPY M15 LONG.  
Live-state at capture: 27 incumbent live strategies unchanged; AUD/JPY M15 LONG is a provisional #28 after historical portfolio testing, not authorised for live orders.  
Principle: Find a reproducible, historically robust region of entry rules and ask whether a frozen addition improves the exact incumbent portfolio. Do not maximise a standalone backtest or backfit a candidate to the portfolio.
The decision sequence at a glance
Define instrument, direction, timeframe, full-history dataset, execution assumptions, incumbent portfolio snapshot and a predeclared core mechanism. Inventory competing mechanisms if relevant.
Prove raw-signal and execution mechanics first. Establish a stable baseline fingerprint and baseline accepted-trade ledger.
Run broad engulfing-first single-factor and structure × body × range scans, preserving informative interactions. Do not declare a pair exhausted because a separate generic-mechanism survey was weak.
Freeze a small number of distinguishable anchors and add one conditional feature at a time within each anchor.
Test a limited set of justified combinations and extend parameter boundaries only where the preceding evidence calls for it.
Map the candidate's range/structure/momentum neighbourhood and examine frequency recovered versus return/drawdown surrendered.
Predeclare a small local multidimensional plateau study; stop entry-rule tuning when the region is intelligible.
With entries frozen, run a limited RR sweep with full chronological trade replay at each RR and at every assumed fill cost.
Freeze a primary core and at most a genuinely useful alternative such as a frequency comparator. Independently reimplement and match complete accepted-trade ledgers.
Test the exact frozen Portfolio N → N+1 comparison (all costs, equity/risk rules, pair gates, contemporaneous risk and rolling years). If historically admissible, proceed to a read-only live probe and actual-fill study before even considering orders.
Stages are evidence gates, not a rule that every candidate must receive every stage. Stop early when raw structure or cost stress fails broadly, when gains live only at an untested boundary, or when exact portfolio addition harms essential portfolio risk properties. Archive unsuccessful mechanisms honestly; avoid converting repeated failures into unlimited searching.
---
Setup: common controls and non-negotiables
Before any optimisation, write a frozen protocol specifying:
Pair, broker price source, M15/H1/D1 timeframe, LONG/SHORT, exact pattern logic, timestamp and timezone conventions, holidays/gaps, indicator warm-up and lookahead policy.
Full candle start/end timestamps, candle count, source/raw-signal hash, instrument precision, pip and tick size, midpoint/bid/ask definitions and order/fill conventions.
Stop/target convention, assumed entry penalty and any extra cost/slippage, exact R denominator, intrabar stop-versus-target resolution, signal/entry/exit bar handling, pyramiding-zero and same-pair non-hedging rules.
Reference RR for entry discovery; a paired ordinary and stressed fill assumption (AUD/JPY example: 2 and 4 adverse pips, assumed, not measured historic quotes).
Independent period boundaries; calendar years and rolling 12/24/36-month windows; clear treatment of zero-trade periods, unfinished years and right-censoring.
Target incumbent portfolio version, accepted ledger hash, portfolio cutoff, account currency conversion, risk per trade, realised-equity compounding, constraints and any existing signals unavailable for counterfactual replay.
A research runner must be read-only, separate from the live executor, and fail closed on source/control/parity failures. Never mutate live strategies because a research grid performed well.
AUD/JPY example: JPY pip = 0.01, tick = 0.001; long stop = signal low − 10 ticks; exact bullish engulf; stop/target from the specified reference-risk implementation; no weekday/session optimisation in this project. The final independent run explicitly described historical OANDA MID candles and 2/4-pip assumed adverse fills.
Pass 1 — broad, controlled engulfing-first discovery
Question: Is there a coherent engulfing-based edge after plausible structure/quality filters, despite the raw engulfing baseline being noisy?
Run a raw exact-engulfing stream, then single-factor scans and a controlled grid such as structure lookback × distance from previous low × engulfing body size × candle range. Use one reference RR and both fill costs; report candidate-only trades and complete chronological accepted trades. Do not require every individual factor to be independently profitable before examining plausible structure-dependent effects; equally, do not manufacture endless combinations from null results.
Example: 19,471 raw exact engulfing accepted trades; 169 single-factor settings; 336 structure/body/range combinations. Three frozen entry anchors were deliberately different: tight LB100, tight LB40 and broader LB60. At 4-pip stress, many initially positive 2-pip settings failed; that mattered more than the best unstressed row.
Exit criterion: A few economically interpretable anchors, with counts, fully specified rules and immutable controls. If there is no credible region under stressed costs, record the mechanism as not supported by the tested search, not that the entire pair/direction is impossible.
Pass 2 — one conditional feature at a time, within each frozen anchor
Hold all anchor entry settings and RR fixed. Test one additional filter per branch (e.g. prior movement, M15/H1/D1 volatility regime, previous-bar quality, strong close). Each candidate is compared with its own frozen anchor, not with a moving best-performing control. Record trade adds/removals and full 2-/4-pip stress; report early/recent eras, rolling windows and count deterioration.
Example: 420 one-factor rows, 140 per anchor. BROAD LB60 + previous-192-M15-bar rise ≥0.50 ATR and BROAD + M15 volatility expansion emerged as separate candidates; the tight branch had a distinct completed-D1-ATR feature. Do not assume individually useful filters combine additively.
Exit criterion: Only a few conditional mechanisms with a plausible causal interpretation and neighbouring thresholds worth checking. Identify upper/lower tested boundaries explicitly.
Pass 3 — justified combinations and boundary expansion
Test predeclared, limited interactions suggested by Pass 2; expand only boundary parameters that were constraining interpretation. Keep comparisons branch-labelled. Log the difference between an improvement caused by removing losers and one caused simply by reducing exposure/trade count. Ask whether combined filters actually help after the stressed fill, including both old and newly eligible trades following chronological replay.
Example: 369 configurations including momentum × M15 volatility, body × volatility, tighter-structure × daily/H1 volatility, and revised lookback/distance/range boundaries. The key discovery came from increasing signal range inside the BROAD + momentum setup; adding momentum and volatility together was not automatically better.
Exit criterion: One or two promising, interpretable families; if all gains are at the last tested boundary, the range is still unresolved.
Pass 4 — map plateau and frequency recovery
With a credible family, predeclare a controlled range × preceding-movement study and a structure/lookback × distance study. Extend beyond apparent edge levels where necessary; do not chase indefinitely when the count becomes uninformatively small. Compare marginal accepted trades when loosening body/structure/momentum, not naive differences of separate ledgers—pyramiding-zero means an extra early entry may displace a later one.
Example: 404 settings; signal-range neighbourhood around 1.80–2.00 ATR looked coherent; beyond 2.00 the sample became sparse. Prior-192-M15-bar rise ≥0.50 ATR was not a uniquely special threshold, and broadening low distance raised frequency while weakening some stressed outcomes. "Previous 192 M15 bars" means 48 market hours, not always 48 wall-clock hours.
Exit criterion: Identify stable interior regions, unresolved dimensions, count-versus-stability tradeoffs, and a small local region for one final controlled confirmation.
Pass 5 — local multidimensional plateau confirmation
No new filter hunt. Freeze secondary factors and reference RR. Predeclare a small local grid around a credible central geometry; confirm joint robustness rather than comparing unconnected one-axis winners. Optionally test a very small number of already identified alternative momentum thresholds at representative geometries. Retain a higher-frequency comparator only if it answers a different economic question.
Example: 60 geometries (LB50/60/70 × distance 0.40/0.50/0.60/0.75 ATR × range 1.75/1.80/1.85/1.90/2.00 ATR), plus 9 separate momentum controls. All 60 were lifetime-positive at the 4-pip assumption, but heavily overlapping and in-sample. Core LB60/0.50/1.80 had 95 trades, +60.16R and −7R historical closed drawdown at 4 pips; LB60/0.75/1.80 had 133 trades and +58.27R, with weaker rolling periods. That justified freezing a core and a frequency comparator, not declaring 60 independent wins.
Exit criterion: Entry rules frozen; record why the central rules are retained instead of choosing the largest historical R from a boundary.
Pass 6 — RR last, with full execution replay
With entries frozen, sweep a modest RR range once. Rebuild the exact signal-to-trade chronology separately for every RR and cost, because target duration and pyramiding-zero alter later eligibility. Include trade-level comparisons against a fixed RR control, annual/era figures, trailing 1/2/5 years and rolling 12/24/36 months. Analyse the whole RR neighbourhood and tough periods rather than optimising full-history R.
Example: RR2.50–4.50 in 0.25 increments for both frozen geometries: 18 settings, each at 2/4 pips. The core had a 3.5–4.0 neighbourhood. RR3.5 was retained: +60.16R over 95 trades and −7R historical closed drawdown at 4 pips; RR4.0 gave only ~+1.85R extra lifetime at 4 pips while weakening some rolling outcomes. The 2016–2021 era was still weak; no new regime filter was introduced to "repair" it.
Exit criterion: Immutable written rules; full accepted trade ledgers/digests for frozen primary and comparator at both costs. STOP geometry and RR tuning on this repeatedly inspected history.
Independent standalone confirmation — implementation parity, not fresh OOS
Rebuild indicators, exact signals and execution separately from the exploratory code. Check all accepted trades field by field (signal/entry/exit time, price, stop/target, fill, outcome/R as applicable), counts, ledger hashes and coverage. Check source price type and precision; a simple aggregate R/count match is weaker than complete ledger parity. Any mismatch is a failed gate, not a portfolio result to interpret.
AUD/JPY example: Core 95 and frequency 133 accepted trades at each 2-/4-pip cost independently matched frozen ledgers. This proves coding reproducibility on the same examined history, not untouched out-of-sample predictive validity.
Exact Portfolio N → N+1 admission — only after freeze/parity
Compare the incumbent frozen accepted stream with each predeclared candidate version independently. Check baseline hash/trade count, identical portfolio cutoff, every incumbent strategy preserved, non-hedging/same-pair effects, global position limits if any, time ordering, risk sizing on then-realised balance, base-currency conversion and transaction costs. If a new signal may displace existing same-pair trades or hit a global gate, the incumbent accepted ledger alone may be inadequate: obtain raw streams and replay conflicts; otherwise fail closed.
Required portfolio outputs: unchanged baseline versus addition under ordinary/stressed candidate fills; incremental R/equity impact, max closed and conservative/intratrade DD, tail/concurrent risk, last 1/2/3/5 years, every rolling 12/24/36-month window (especially worst windows), calendar/era results, overlapping AUD/JPY or correlated-currency positions, and counts. Report precisely which baseline cost assumptions remain unchanged.
AUD/JPY example: Exact 3,029-trade / 27-strategy baseline dated 20 Sep 2026 was reproduced; there were no existing AUD/JPY trades and the historical model had no global max-position gate. At assumed 4 pips for the added AUD/JPY only, the historical portfolio return improved with recorded worst drawdown unchanged. The core improved the weakest historical 12M window; frequency comparator improved the weakest historical 24/36M windows more. These are historical portfolio admission observations, not a prospective profitability guarantee. The independently reproduced candidate history extended beyond the portfolio cutoff; never mix cutoffs.
Exit criterion: Explicit classification: rejected, keep for research, or provisionally historically admissible. The portfolio is an admission test, not a new parameter-selection objective; do not reopen the discovery grid when a frozen addition disappoints.
Live probe and deployment are separate, later gates
A historical pass is not permission to trade. Run a read-only OANDA signal probe with exact completed-candle timing and logging for would-be orders, actual bid/ask spreads, spread spikes/time-of-day, stop-distance/fill conventions, currency conversion, broker pair/account mode, executor non-hedging gate, correlated exposure and aggregate risk. Compare real-time probe against frozen research signal semantics and account for broker latency, rejects, costs and live stop/target handling. Require prospective observation; agree deployment controls explicitly before writing orders. Never change the 27-strategy executor in a discovery pass.
Universal reporting / fail-closed checklist
Every result ZIP should contain coverage and cutoff, source fingerprint, hard control/parity results, research grid plus all levels/boundaries, per-configuration summary at both fills, complete frozen ledgers, period/year results, rolling windows incl. zero-trade counts, candidate-only versus full replay attribution, cost sensitivity, methodology and error report if any. Show rejected and weak neighbours, not just selected rows. No strategy conclusion if errors, missing configurations, changed history or failed controls. Synthetic smoke tests validate software plumbing only; do not represent an OANDA full-history run.
The analyst must explicitly separate: raw signals vs accepted trades; candidate-only expectancy vs overall results; close-to-close drawdown vs conservative/intratrade drawdown; past results vs forecasts; stressed assumed fill vs observed executable pricing; aggregate parity vs full-ledger parity; exploratory history vs genuinely unseen prospective validation.
Default instruction to reuse in the next pair/direction
> Use the **Forex strategy research protocol — AUD/JPY M15 LONG template (2026-09-24)**. Start with a documented engulfing-first baseline and controlled structure/body/range matrix, even if other previously tested mechanisms on that pair were disappointing. Establish raw candle/signal fingerprints; predeclare stages and ordinary/stressed fill assumptions. Discover one-factor effects and structural interactions, freeze multiple distinct anchors only where justified, test limited conditional combinations, investigate boundary/plateau and frequency marginal trades, then do one small local multidimensional confirmation. Freeze entry geometry **before** a limited RR sweep. Replay all orders chronologically under each RR/cost. Independently reproduce full accepted ledgers and run the exact incumbent Portfolio N→N+1 addition as a final historical admission gate, never as an optimisation target. Report all weak rolling periods, concurrency, costs, and implementation limitations. Treat repeatedly examined data as in-sample. Preserve live strategies and executor unchanged; require read-only forward execution probing before proposing live orders. Stop honestly when a stage fails rather than searching without end.
Associated case-study artifacts
`audjpy_engulf_matrix.py` and `AUDJPY_M15_LONG_ENGULFING_MATRIX_PASS1_RESULTS.zip`
`AUDJPY_M15_LONG_ENGULFING_PASS2_CONDITIONAL_FEATURES_FIXED.py` and `AUDJPY_M15_LONG_ENGULFING_PASS2_RESULTS (1).zip` (the similarly named Pass 2 ZIP without `(1)` was an error report)
`AUDJPY_M15_LONG_ENGULFING_PASS3_COMBINATIONS_BOUNDARIES.py` / `AUDJPY_M15_LONG_ENGULFING_PASS3_RESULTS.zip`
`AUDJPY_M15_LONG_ENGULFING_PASS4_PLATEAU_FREQUENCY.py` / `AUDJPY_M15_LONG_ENGULFING_PASS4_RESULTS.zip`
`AUDJPY_M15_LONG_ENGULFING_PASS5_LOCAL_PLATEAU.py` / `AUDJPY_M15_LONG_ENGULFING_PASS5_RESULTS.zip`
`AUDJPY_M15_LONG_ENGULFING_PASS6_RR_STANDALONE.py` / `AUDJPY_M15_LONG_ENGULFING_PASS6_RESULTS.zip`
`AUDJPY_M15_LONG_INDEPENDENT_27_TO_28.py` / `AUDJPY_M15_LONG_FROZEN_27_TO_28_RESULTS.zip`
Scope note: This describes the process we used, including limitations and stage-specific decisions. It is a template for research discipline, not a requirement that new instruments pass the same thresholds, produce the same trade counts, or admit a candidate after a fixed number of passes.
